In [1]:
import pandas as pd
import numpy as np


In [2]:
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import make_classification

In [8]:
x,y = make_classification(n_samples=10000,n_features=3,n_classes=2,n_redundant=1,random_state=42)

In [9]:
x

array([[ 0.77144029, -0.03909349, -1.26233499],
       [-1.2921157 ,  0.92631278, -0.40911066],
       [-1.42722051,  0.31661032,  1.6193163 ],
       ...,
       [ 1.28657493, -0.66586829, -0.34446599],
       [ 1.04275178, -0.18116461, -1.33012838],
       [-0.90758902,  0.25964617,  0.85881751]])

In [10]:
y

array([0, 0, 1, ..., 0, 1, 1])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
classifier = KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [17]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [18]:
classifier.get_params

<bound method BaseEstimator.get_params of KNeighborsClassifier()>

In [19]:
y_pred = classifier.predict(x_test)

In [20]:
y_pred

array([1, 0, 0, ..., 1, 1, 1])

In [21]:
y_test

array([1, 0, 0, ..., 1, 1, 1])

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [23]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[938  61]
 [ 75 926]]
0.932
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       999
           1       0.94      0.93      0.93      1001

    accuracy                           0.93      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.93      0.93      0.93      2000



In [24]:
#Hyperparameter tunning

In [25]:
from sklearn.model_selection import GridSearchCV

In [29]:
parameter = {
    'n_neighbors':[5,10,15],
    'weights':['uniform','distance'],
    'algorithm':['auto'],
    'p':[1,2],
    'n_jobs':[1,2,-1],
    }

In [30]:
clf  = GridSearchCV(KNeighborsClassifier(),param_grid=parameter,cv=5,refit=True,verbose=3)

In [31]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV 1/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=uniform;, score=0.928 total time=   0.0s
[CV 2/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=uniform;, score=0.932 total time=   0.0s
[CV 3/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=uniform;, score=0.934 total time=   0.0s
[CV 4/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=uniform;, score=0.941 total time=   0.0s
[CV 5/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=uniform;, score=0.936 total time=   0.0s
[CV 1/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=distance;, score=0.926 total time=   0.0s
[CV 2/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=distance;, score=0.926 total time=   0.0s
[CV 3/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=distance;, score=0.930 total time=   0.0s
[CV 4/5] END algorithm=auto, n_jobs=1, n_neighbors=5, p=1, weights=dist

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto'], 'n_jobs': [1, 2, -1],
                         'n_neighbors': [5, 10, 15], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [32]:
clf.best_params_

{'algorithm': 'auto',
 'n_jobs': 1,
 'n_neighbors': 15,
 'p': 1,
 'weights': 'uniform'}

In [33]:
classifier = KNeighborsClassifier(algorithm='auto',n_jobs=1,n_neighbors=15,p=1,weights='uniform')

In [34]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_jobs=1, n_neighbors=15, p=1)

In [35]:
y_pred = classifier.predict(x_test)

In [36]:
confusion_matrix(y_test,y_pred)

array([[935,  78],
       [ 57, 930]], dtype=int64)

In [37]:
accuracy_score(y_pred,y_test)

0.9325