In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report


In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
df['species'] = df['species'].map({'setosa':0,'versicolor':1,'virginica':2})

In [8]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [9]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [10]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [11]:
classifier = LogisticRegression(multi_class='multinomial',solver='lbfgs')

In [15]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [16]:
classifier.fit(x_train,y_train)

LogisticRegression(multi_class='multinomial')

In [17]:
y_pred = classifier.predict(x_test)

In [19]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [21]:
list(y_test)

[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0]

In [22]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [23]:
classifier.predict_proba(x_test)

array([[3.78447627e-03, 8.27195276e-01, 1.69020248e-01],
       [9.46734340e-01, 5.32654604e-02, 2.00060208e-07],
       [8.71443395e-09, 1.55607701e-03, 9.98443914e-01],
       [6.43381072e-03, 7.92133797e-01, 2.01432392e-01],
       [1.44065771e-03, 7.74230278e-01, 2.24329064e-01],
       [9.55793445e-01, 4.42063784e-02, 1.76848115e-07],
       [7.76293985e-02, 9.08065089e-01, 1.43055122e-02],
       [1.61350816e-04, 1.55663871e-01, 8.44174778e-01],
       [2.20830246e-03, 7.62721557e-01, 2.35070141e-01],
       [2.83223103e-02, 9.45786093e-01, 2.58915967e-02],
       [4.39539974e-04, 2.43310467e-01, 7.56249993e-01],
       [9.68331867e-01, 3.16680549e-02, 7.80375880e-08],
       [9.72948832e-01, 2.70511350e-02, 3.33416376e-08],
       [9.62120710e-01, 3.78791795e-02, 1.10894772e-07],
       [9.79275201e-01, 2.07247344e-02, 6.47385561e-08],
       [4.54072396e-03, 7.12636783e-01, 2.82822493e-01],
       [7.22464694e-06, 2.42121732e-02, 9.75780602e-01],
       [2.73388797e-02, 9.47678