In [5]:
import tensorflow as tf
import keras

In [6]:
print("Tensorflow version {}".format(tf.__version__))
print('Keras Version {}'.format(keras.__version__))

Tensorflow version 2.16.1
Keras Version 3.2.1


In [7]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [8]:
import tensorflow as tf

In [10]:
age = tf.constant(21)

In [11]:
age

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [12]:
age.numpy()

21

In [14]:
marks = tf.constant(23,dtype=float)

In [15]:
marks

<tf.Tensor: shape=(), dtype=float32, numpy=23.0>

In [16]:
marks.dtype

tf.float32

In [17]:
marks.numpy()

23.0

In [18]:
arr = tf.constant([[1,2],[3,4]])

In [19]:
arr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
arr.numpy()

array([[1, 2],
       [3, 4]])

In [32]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [33]:
print(tf.zeros((2,4)))

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)


In [34]:
a1 = tf.constant([[1,2],[3,4]])
a2 = tf.constant([[1,2],[3,4]])
result = tf.add(a1,a2)

In [35]:
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>

In [36]:
tf.random.normal((2,3),mean=0,stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.56118816, -0.2075056 ,  1.5500028 ],
       [ 1.0478423 , -1.3819695 ,  0.59160846]], dtype=float32)>

In [38]:
tf.random.uniform((2,3),minval=1,maxval=10,dtype=float)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.7619731, 6.8910666, 8.87895  ],
       [8.752268 , 5.51241  , 8.765076 ]], dtype=float32)>

In [39]:
var0 = 12

In [40]:
var0 = tf.Variable(21)

In [42]:
var0.numpy()

21

In [43]:
var1 = tf.Variable([[1,2],[3,4],[5,6]])

In [44]:
var1

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [45]:
var_res = tf.Variable(12.)

In [46]:
var_res

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=12.0>

In [47]:
var_res.assign(222.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=222.0>

In [48]:
var_res.assign(32)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=32.0>

In [51]:
data =  tf.Variable([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [52]:
data

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [55]:
d1 = tf.reshape(data,[6,2])

In [56]:
d1

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [57]:
tf.rank(data)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [61]:
d1 = tf.Variable(([[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]))

In [62]:
d1

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])>

In [63]:
d1[1,0,2]

<tf.Tensor: shape=(), dtype=int32, numpy=33>

In [64]:
d1[1,0,2].numpy()

33

In [65]:
tf.size(input=d1).numpy()

12

In [66]:
d1.dtype

tf.int32

In [68]:
a = tf.random.normal((2,3))
b = tf.random.normal((2,3))
c = a+b
d = tf.sqrt(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.9713085   0.57644045  0.5526989 ]
 [ 2.0937166  -0.1975025   0.34698838]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.08467546 -0.42586422  1.2578441 ]
 [ 0.09171568  0.92194027 -0.29854962]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2.055984   0.15057623 1.8105431 ]
 [2.1854322  0.7244378  0.04843876]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1.4338703  0.38804153 1.3455642 ]
 [1.4783207  0.8511391  0.22008806]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[7.8145237 1.162504  6.1137667]
 [8.894492  2.0635705 1.0496311]], shape=(2, 3), dtype=float32)


In [69]:
a*b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.16692145, -0.24548537,  0.6952091 ],
       [ 0.19202664, -0.1820855 , -0.10359325]], dtype=float32)>

In [70]:
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.9713085 ,  0.57644045,  0.5526989 ],
       [ 2.0937166 , -0.1975025 ,  0.34698838]], dtype=float32)>

In [71]:
a*4

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 7.885234 ,  2.3057618,  2.2107956],
       [ 8.3748665, -0.79001  ,  1.3879535]], dtype=float32)>