In [1]:
import numpy as np
import pandas as pd

In [2]:
l = [1,2,3,4,5]

In [3]:
l

[1, 2, 3, 4, 5]

In [4]:
np.array(l)

array([1, 2, 3, 4, 5])

In [5]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1 = np.array(l)

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1.ndim

1

In [10]:
arr1.size

5

In [11]:
arr1.dtype

dtype('int32')

In [12]:
c = arr1#Solw copy 

In [13]:
c

array([1, 2, 3, 4, 5])

In [14]:
c[0] = 90

In [17]:
arr1

array([90,  2,  3,  4,  5])

In [18]:
c

array([90,  2,  3,  4,  5])

In [29]:
d = arr1.copy() #Deep copy

In [30]:
d

array([999,   2,   3,   4,   5])

In [31]:
d[0] = 999

In [32]:
d

array([999,   2,   3,   4,   5])

In [33]:
arr1

array([999,   2,   3,   4,   5])

In [34]:
d[0] = 99999

In [35]:
d

array([99999,     2,     3,     4,     5])

In [36]:
arr1

array([999,   2,   3,   4,   5])

In [37]:
np.fromfunction(lambda x,y:x==y,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [38]:
np.fromfunction(lambda x,y:x*y,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [39]:
np.fromstring("1,2,3,4,5",sep=",")

array([1., 2., 3., 4., 5.])

In [40]:
np.fromstring("1 2 3 4 5",sep=" ")

array([1., 2., 3., 4., 5.])

In [42]:
iter  = (i for i in range(5))

In [44]:
np.fromiter(iter,dtype=int)

array([0, 1, 2, 3, 4])

In [45]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [46]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [48]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.ones((5,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [54]:
np.ones((3,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [55]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
np.logspace(3,4,10)

array([ 1000.        ,  1291.54966501,  1668.1005372 ,  2154.43469003,
        2782.55940221,  3593.8136638 ,  4641.58883361,  5994.84250319,
        7742.63682681, 10000.        ])

In [60]:
np.logspace(3,4,10,base=2)

array([ 8.        ,  8.64047791,  9.33223232, 10.0793684 , 10.88632   ,
       11.75787594, 12.69920842, 13.71590373, 14.8139954 , 16.        ])

In [65]:
np.random.randn(3,3)#mean = 0,std=1

array([[-2.06614013, -0.12446909, -0.45500334],
       [ 0.25491717,  0.99611902,  0.88124445],
       [-0.44009729, -0.55000857, -0.26969952]])

In [63]:
np.random.rand(3,3)

array([[0.14952815, 0.52506153, 0.49370189],
       [0.84875568, 0.78478324, 0.682321  ],
       [0.97619114, 0.98934031, 0.37073649]])

In [66]:
arr2 = np.random.randint(1,10,(5,5))

In [67]:
arr2.ndim

2

In [68]:
arr2.dtype

dtype('int32')

In [69]:
arr2.size

25

In [70]:
arr = np.random.randint(1,10,(4,3))

In [71]:
arr

array([[5, 9, 1],
       [2, 9, 3],
       [9, 7, 7],
       [1, 6, 3]])

In [76]:
arr = arr.reshape(3,4)

In [77]:
arr[0:3,3]

array([2, 7, 3])

In [78]:
arr

array([[5, 9, 1, 2],
       [9, 3, 9, 7],
       [7, 1, 6, 3]])

In [79]:
arr[1:3,[1,2]]

array([[3, 9],
       [1, 6]])

In [80]:
arr[arr>5]

array([9, 9, 9, 7, 7, 6])

In [81]:
arr1 = np.random.randint(1,10,(3,4))

In [82]:
arr2 = np.random.randint(1,5,(3,4))

In [83]:
arr1

array([[5, 9, 8, 6],
       [3, 5, 3, 6],
       [5, 7, 7, 8]])

In [84]:
arr2

array([[2, 2, 2, 1],
       [4, 2, 1, 1],
       [3, 2, 1, 2]])

In [85]:
arr1+arr2

array([[ 7, 11, 10,  7],
       [ 7,  7,  4,  7],
       [ 8,  9,  8, 10]])

In [86]:
arr1-arr2

array([[ 3,  7,  6,  5],
       [-1,  3,  2,  5],
       [ 2,  5,  6,  6]])

In [87]:
arr*arr2

array([[10, 18,  2,  2],
       [36,  6,  9,  7],
       [21,  2,  6,  6]])

In [90]:
arr1@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [91]:
arr1.T

array([[5, 3, 5],
       [9, 5, 7],
       [8, 3, 7],
       [6, 6, 8]])

In [92]:
arr1

array([[5, 9, 8, 6],
       [3, 5, 3, 6],
       [5, 7, 7, 8]])

In [93]:
arr1.T@arr2

array([[37, 26, 18, 18],
       [59, 42, 30, 28],
       [49, 36, 26, 25],
       [60, 40, 26, 28]])

In [94]:
np.sqrt(arr1)

array([[2.23606798, 3.        , 2.82842712, 2.44948974],
       [1.73205081, 2.23606798, 1.73205081, 2.44948974],
       [2.23606798, 2.64575131, 2.64575131, 2.82842712]])

In [95]:
np.mean(arr1)

6.0

In [96]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
np.empty((3,3))

array([[2.06614013, 0.12446909, 0.45500334],
       [0.25491717, 0.99611902, 0.88124445],
       [0.44009729, 0.55000857, 0.26969952]])