In [1]:
import numpy as np

In [2]:
l = [12,4,34,76,89]

In [3]:
l

[12, 4, 34, 76, 89]

In [4]:
np.array(l)

array([12,  4, 34, 76, 89])

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
np.asanyarray(l)

array([12,  4, 34, 76, 89])

In [7]:
np.asarray(l)

array([12,  4, 34, 76, 89])

In [8]:
np.matrix(l)#Matrix is subset of array

matrix([[12,  4, 34, 76, 89]])

In [9]:
type(np.matrix(l))

numpy.matrix

In [10]:
type(np.array(l))

numpy.ndarray

In [11]:
a = np.array(l)

In [12]:
a

array([12,  4, 34, 76, 89])

In [13]:
c=a#slow copy

In [14]:
a

array([12,  4, 34, 76, 89])

In [15]:
c

array([12,  4, 34, 76, 89])

In [17]:
c[0] = 90

In [18]:
c

array([90,  4, 34, 76, 89])

In [19]:
a

array([90,  4, 34, 76, 89])

In [25]:
d = a.copy()#deep copy 


In [26]:
a

array([ 1,  4, 34, 76, 89])

In [27]:
d

array([ 1,  4, 34, 76, 89])

In [28]:
a[0]= 76

In [29]:
a

array([76,  4, 34, 76, 89])

In [30]:
d

array([ 1,  4, 34, 76, 89])

In [31]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j:i*j,(4,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [34]:
np.fromstring("2 43 56 43 34 54",sep=" ")

array([ 2., 43., 56., 43., 34., 54.])

In [35]:
np.fromstring("12,23,54,67,87,98,78",sep=",")

array([12., 23., 54., 67., 87., 98., 78.])

In [37]:
iter = (i for i in range(5))

In [39]:
np.fromiter(iter,dtype=int)

array([0, 1, 2, 3, 4])

In [40]:
l1 = [21,43,56,87,65]

In [41]:
arr = np.array(l1)

In [42]:
arr.shape

(5,)

In [43]:
arr.ndim

1

In [44]:
arr.dtype

dtype('int32')

In [45]:
arr.size

5

In [46]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [47]:
type(arr2)

numpy.ndarray

In [48]:
arr2.ndim

2

In [49]:
arr2.dtype

dtype('int32')

In [51]:
arr2.size

8

In [53]:
np.arange(1.5,2.5,0.1)

array([1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4])

In [54]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.zeros((4,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [58]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [60]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.ones((3,4,5))+9

array([[[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]])

In [63]:
np.ones((3,4,5))*67

array([[[67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.]],

       [[67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.]],

       [[67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.],
        [67., 67., 67., 67., 67.]]])

In [65]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [68]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [71]:
np.random.randn(3,4)

array([[-2.0327203 , -0.45374883,  0.1324257 , -1.23308478],
       [-0.88473923, -0.93529198, -0.82283108,  0.30688368],
       [-0.45245069,  2.02381299, -1.72468769,  0.32333053]])

In [72]:
import pandas as pd

In [73]:
pd.DataFrame(np.random.randn(3,4))

0         1         2         3
0 -0.673428  0.613610  0.531493  0.381521
1 -0.804412 -1.996008  0.849903  1.240326
2  1.175932 -1.221908  0.308843  0.960895

In [74]:
np.random.rand(3,4)

array([[0.5239102 , 0.25835346, 0.13338274, 0.80650147],
       [0.30393949, 0.22687336, 0.19215173, 0.81550741],
       [0.12070736, 0.36753712, 0.21226887, 0.02467607]])

In [75]:
np.random.randint(1,100,(3,5))

array([[73, 63, 95, 89, 46],
       [56, 21, 30, 38, 36],
       [96, 90,  6, 47, 94]])

In [76]:
arr

array([21, 43, 56, 87, 65])

In [77]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
arr2 = arr2.reshape(4,2)

In [81]:
arr2[1][1]

4

In [82]:
arr = np.random.randint(1,100,(5,5))

In [83]:
arr

array([[ 4, 41, 81, 17, 28],
       [50, 23, 85, 75, 65],
       [40, 31, 83,  9, 22],
       [54, 26, 46, 43, 31],
       [28, 79, 91, 95, 71]])

In [84]:
arr>50

array([[False, False,  True, False, False],
       [False, False,  True,  True,  True],
       [False, False,  True, False, False],
       [ True, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [85]:
arr[arr>50]

array([81, 85, 75, 65, 83, 54, 79, 91, 95, 71])

In [87]:
arr[0:5,4]

array([28, 65, 22, 31, 71])

In [88]:
arr

array([[ 4, 41, 81, 17, 28],
       [50, 23, 85, 75, 65],
       [40, 31, 83,  9, 22],
       [54, 26, 46, 43, 31],
       [28, 79, 91, 95, 71]])

In [89]:
arr[2:4,[1,2]]

array([[31, 83],
       [26, 46]])

In [90]:
a1 = np.random.randint(1,3,(3,3))

In [91]:
a2 = np.random.randint(1,5,(3,3))

In [92]:
a1+a2

array([[5, 4, 3],
       [5, 4, 3],
       [2, 2, 5]])

In [93]:
a1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [94]:
a2

array([[3, 3, 2],
       [3, 2, 2],
       [1, 1, 4]])

In [95]:
a1*a2

array([[6, 3, 2],
       [6, 4, 2],
       [1, 1, 4]])

In [96]:
a1-a2

array([[-1, -2, -1],
       [-1,  0, -1],
       [ 0,  0, -3]])

In [98]:
a1@a2

array([[10,  9, 10],
       [13, 11, 12],
       [ 7,  6,  8]])

In [99]:
a1

array([[2, 1, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [100]:
a2

array([[3, 3, 2],
       [3, 2, 2],
       [1, 1, 4]])

In [101]:
a2/0

C:\Users\shekh\AppData\Local\Temp\ipykernel_11756\1664676690.py:1: RuntimeWarning: divide by zero encountered in divide
  a2/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [102]:
a2**2

array([[ 9,  9,  4],
       [ 9,  4,  4],
       [ 1,  1, 16]])

In [103]:
a1 = np.zeros((3,3))

In [104]:
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
a2 = np.array([1,2,3])

In [109]:
a2

array([1, 2, 3])

In [110]:
a1+a2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [113]:
a2 = np.array([[1,2,3]])

In [114]:
a2.T

array([[1],
       [2],
       [3]])

In [115]:
a1+a2.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [116]:
arr1 = np.random.randint(3,4,(3,3))

In [117]:
arr1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [118]:
arr1.mean()

3.0

In [119]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081]])

In [120]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125],
       [0.47712125, 0.47712125, 0.47712125],
       [0.47712125, 0.47712125, 0.47712125]])