In [1]:
import numpy as np

In [2]:
arr  =  np.random.randint(1,10,(3,4))

In [3]:
arr

array([[5, 1, 5, 9],
       [7, 6, 4, 1],
       [3, 4, 3, 6]])

In [4]:
arr.ndim

2

In [5]:
arr.reshape(4,3)

array([[5, 1, 5],
       [9, 7, 6],
       [4, 1, 3],
       [4, 3, 6]])

In [6]:
arr.flatten()

array([5, 1, 5, 9, 7, 6, 4, 1, 3, 4, 3, 6])

In [7]:
arr1 = np.array([[1],[2],[3]])

In [8]:
arr1

array([[1],
       [2],
       [3]])

In [9]:
arr1.squeeze()

array([1, 2, 3])

In [10]:
arr2 = np.array([1,2,3,4])

In [11]:
arr2

array([1, 2, 3, 4])

In [13]:
np.expand_dims(arr2,axis=0)

array([[1, 2, 3, 4]])

In [14]:
arr2

array([1, 2, 3, 4])

In [15]:
np.roll(arr2,2)

array([3, 4, 1, 2])

In [16]:
np.repeat(arr2,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [17]:
np.diag(arr2)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [20]:
arr1

array([[3, 3, 7, 2],
       [6, 9, 7, 8],
       [8, 8, 9, 5]])

In [21]:
arr2

array([[6, 3, 7, 1],
       [3, 4, 1, 1],
       [2, 7, 7, 4]])

In [22]:
arr1+arr2

array([[ 9,  6, 14,  3],
       [ 9, 13,  8,  9],
       [10, 15, 16,  9]])

In [23]:
arr1-arr2

array([[-3,  0,  0,  1],
       [ 3,  5,  6,  7],
       [ 6,  1,  2,  1]])

In [24]:
arr*arr2

array([[30,  3, 35,  9],
       [21, 24,  4,  1],
       [ 6, 28, 21, 24]])

In [25]:
arr1%arr2

array([[3, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 2, 1]])

In [26]:
arr

array([[5, 1, 5, 9],
       [7, 6, 4, 1],
       [3, 4, 3, 6]])

In [27]:
arr1&arr2

array([[2, 3, 7, 0],
       [2, 0, 1, 0],
       [0, 0, 1, 4]])

In [28]:
arr1|arr2

array([[ 7,  3,  7,  3],
       [ 7, 13,  7,  9],
       [10, 15, 15,  5]])

In [29]:
arr = np.array(["arjun","singh"])

In [30]:
arr

array(['arjun', 'singh'], dtype='<U5')

In [31]:
np.char.title(arr)

array(['Arjun', 'Singh'], dtype='<U5')

In [32]:
np.char.upper(arr)

array(['ARJUN', 'SINGH'], dtype='<U5')

In [33]:
np.char.capitalize(arr)

array(['Arjun', 'Singh'], dtype='<U5')

In [34]:
np.mean(arr1)

6.25

In [35]:
np.std(arr1)

2.3496453633119474

In [36]:
np.var(arr1)

5.520833333333333

In [37]:
np.min(arr1)

2

In [38]:
np.max(arr1)

9