In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,100,(4,3))

In [5]:
arr

array([[19, 67, 32],
       [59, 62, 45],
       [17, 88, 70],
       [60, 78, 21]])

In [6]:
arr.reshape(3,4)

array([[19, 67, 32, 59],
       [62, 45, 17, 88],
       [70, 60, 78, 21]])

In [7]:
arr.T

array([[19, 59, 17, 60],
       [67, 62, 88, 78],
       [32, 45, 70, 21]])

In [8]:
arr.flatten()

array([19, 67, 32, 59, 62, 45, 17, 88, 70, 60, 78, 21])

In [9]:
arr

array([[19, 67, 32],
       [59, 62, 45],
       [17, 88, 70],
       [60, 78, 21]])

In [10]:
arr1 = np.array([1,2,3,4,5])

In [11]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [14]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
np.squeeze(arr)

array([[19, 67, 32],
       [59, 62, 45],
       [17, 88, 70],
       [60, 78, 21]])

In [17]:
arr3 = np.array([[1],[2],[3]])

In [18]:
arr3

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(arr3)

array([1, 2, 3])

In [20]:
arr3.flatten()

array([1, 2, 3])

In [21]:
np.repeat(arr1,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [22]:
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [24]:
arr1 = np.random.randint(1,10,(3,4))

In [25]:
arr2 = np.random.randint(1,10,(3,4))

In [26]:
arr1

array([[9, 9, 4, 5],
       [4, 7, 2, 3],
       [8, 5, 6, 8]])

In [27]:
arr2

array([[7, 7, 7, 9],
       [2, 8, 2, 8],
       [7, 4, 4, 6]])

In [28]:
arr1+arr2

array([[16, 16, 11, 14],
       [ 6, 15,  4, 11],
       [15,  9, 10, 14]])

In [29]:
arr1-arr2

array([[ 2,  2, -3, -4],
       [ 2, -1,  0, -5],
       [ 1,  1,  2,  2]])

In [30]:
arr1*arr2

array([[63, 63, 28, 45],
       [ 8, 56,  4, 24],
       [56, 20, 24, 48]])

In [31]:
arr1/arr2

array([[1.28571429, 1.28571429, 0.57142857, 0.55555556],
       [2.        , 0.875     , 1.        , 0.375     ],
       [1.14285714, 1.25      , 1.5       , 1.33333333]])

In [33]:
arr1.T@arr2

array([[127, 127, 103, 161],
       [112, 139,  97, 167],
       [ 74,  68,  56,  88],
       [ 97,  91,  73, 117]])

In [34]:
arr1%arr2

array([[2, 2, 4, 5],
       [0, 7, 0, 3],
       [1, 1, 2, 2]])

In [36]:
arr1**2

array([[81, 81, 16, 25],
       [16, 49,  4,  9],
       [64, 25, 36, 64]])

In [37]:
arr1&arr2

array([[1, 1, 4, 1],
       [0, 0, 2, 0],
       [0, 4, 4, 0]])

In [38]:
arr1|arr2

array([[15, 15,  7, 13],
       [ 6, 15,  2, 11],
       [15,  5,  6, 14]])

In [39]:
arr1

array([[9, 9, 4, 5],
       [4, 7, 2, 3],
       [8, 5, 6, 8]])

In [40]:
~arr1

array([[-10, -10,  -5,  -6],
       [ -5,  -8,  -3,  -4],
       [ -9,  -6,  -7,  -9]])

In [41]:
arr1

array([[9, 9, 4, 5],
       [4, 7, 2, 3],
       [8, 5, 6, 8]])

In [42]:
arr2

array([[7, 7, 7, 9],
       [2, 8, 2, 8],
       [7, 4, 4, 6]])

In [44]:
bin(arr1[0][0])

'0b1001'

In [45]:
bin(arr2[0][0])

'0b111'

In [46]:
arr = np.array(["arjun","singh"])

In [47]:
arr

array(['arjun', 'singh'], dtype='<U5')

In [48]:
np.char.upper(arr)

array(['ARJUN', 'SINGH'], dtype='<U5')

In [49]:
np.char.capitalize(arr)

array(['Arjun', 'Singh'], dtype='<U5')

In [51]:
np.char.strip(arr)

array(['arjun', 'singh'], dtype='<U5')

In [52]:
np.char.title(arr)

array(['Arjun', 'Singh'], dtype='<U5')

In [54]:
arr1

array([[9, 9, 4, 5],
       [4, 7, 2, 3],
       [8, 5, 6, 8]])

In [55]:
np.sin(arr1)

array([[ 0.41211849,  0.41211849, -0.7568025 , -0.95892427],
       [-0.7568025 ,  0.6569866 ,  0.90929743,  0.14112001],
       [ 0.98935825, -0.95892427, -0.2794155 ,  0.98935825]])

In [56]:
np.cos(arr1)

array([[-0.91113026, -0.91113026, -0.65364362,  0.28366219],
       [-0.65364362,  0.75390225, -0.41614684, -0.9899925 ],
       [-0.14550003,  0.28366219,  0.96017029, -0.14550003]])

In [57]:
np.tan(arr1)

array([[-0.45231566, -0.45231566,  1.15782128, -3.38051501],
       [ 1.15782128,  0.87144798, -2.18503986, -0.14254654],
       [-6.79971146, -3.38051501, -0.29100619, -6.79971146]])

In [58]:
np.log2(arr1)

array([[3.169925  , 3.169925  , 2.        , 2.32192809],
       [2.        , 2.80735492, 1.        , 1.5849625 ],
       [3.        , 2.32192809, 2.5849625 , 3.        ]])

In [59]:
np.power(arr1,2)

array([[81, 81, 16, 25],
       [16, 49,  4,  9],
       [64, 25, 36, 64]], dtype=int32)

In [60]:
np.mean(arr1)

5.833333333333333

In [62]:
np.std(arr1)

2.266911751455907

In [63]:
np.var(arr1)

5.138888888888888

In [64]:
np.min(arr1)

2

In [65]:
np.max(arr1)

9