In [1]:
import numpy as np

In [2]:
arr  = np.array([4,3,1,6,5])

In [3]:
arr

array([4, 3, 1, 6, 5])

In [4]:
arr.sort()

In [5]:
arr

array([1, 3, 4, 5, 6])

In [6]:
np.where(arr>4)

(array([3, 4], dtype=int64),)

In [7]:
arr1 = np.array([4,2,3,0,0,9,0,7,6,0,5])

In [8]:
np.count_nonzero(arr1)

7

In [9]:
np.extract(arr1>0,arr1)

array([4, 2, 3, 9, 7, 6, 5])

In [11]:
np.searchsorted(arr1,4)

5

In [12]:
arr1

array([4, 2, 3, 0, 0, 9, 0, 7, 6, 0, 5])

In [13]:
arr1.byteswap()

array([ 67108864,  33554432,  50331648,         0,         0, 150994944,
               0, 117440512, 100663296,         0,  83886080])

In [14]:
import numpy.matlib as mlt

In [16]:
mlt.ones(4)

matrix([[1., 1., 1., 1.]])

In [17]:
mlt.zeros(3)

matrix([[0., 0., 0.]])

In [18]:
mlt.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [19]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

In [20]:
arr1@arr2

array([[ 7, 10],
       [15, 22]])

In [21]:
np.dot(arr1,arr2)

array([[ 7, 10],
       [15, 22]])