In [1]:
import numpy as np

In [2]:
#Sorting,Search and Counting

In [5]:
arr = np.array([1,12,3,24,5])

In [6]:
arr

array([ 1, 12,  3, 24,  5])

In [7]:
arr.sort()

In [8]:
arr

array([ 1,  3,  5, 12, 24])

In [10]:
np.searchsorted(arr,4)

2

In [13]:
arr1 = np.array([0,32,54,3,54,7,0,0,0,0,0,4,4,0])

In [14]:
arr1

array([ 0, 32, 54,  3, 54,  7,  0,  0,  0,  0,  0,  4,  4,  0])

In [15]:
np.count_nonzero(arr1)

7

In [16]:
arr1

array([ 0, 32, 54,  3, 54,  7,  0,  0,  0,  0,  0,  4,  4,  0])

In [17]:
np.where(arr1>7)

(array([1, 2, 4], dtype=int64),)

In [18]:
np.extract(arr1>7,arr1)

array([32, 54, 54])

In [19]:
arr.byteswap()

array([ 16777216,  50331648,  83886080, 201326592, 402653184])

In [20]:
a = arr.view()#solw copy

In [21]:
import numpy.matlib as mlt

In [22]:
mlt.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [27]:
mlt.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [28]:
mlt.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [29]:
mlt.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

In [31]:
np.dot(arr1,arr2)

array([[ 7, 10],
       [15, 22]])

In [32]:
arr1

array([[1, 2],
       [3, 4]])

In [33]:
arr2

array([[1, 2],
       [3, 4]])

In [34]:
arr1@arr2

array([[ 7, 10],
       [15, 22]])