Q1.Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

ans  The variable list and array list , implementation wise there is not difference because 

1.List and array both are  follow forward and backword index accessing.

2.List and aray both are follow slicing concept.

3.List and array both are follow mutability concept.

But there is some difference between array and list

1.performance - array performance faster as compare to list because array is implemented in c.

2.Homogenity - Array are store homogeneous type data but list store all type of data.

3.Dimentional - list in python is single dimention but array in numpy multi-dimention.

In [19]:
l = ["arjun",True,12+9j,"Data science"]

In [3]:
import numpy as np

In [4]:
arr = np.array(l)

In [5]:
arr

array(['arjun', 'True', '(12+9j)', 'Data science'], dtype='<U64')

In [6]:
l[1] = "Kesav"

In [7]:
l

['arjun', 'Kesav', (12+9j), 'Data science']

In [8]:
arr[1] = "Kesav"

In [9]:
arr

array(['arjun', 'Kesav', '(12+9j)', 'Data science'], dtype='<U64')

In [10]:
l[-1]

'Data science'

In [11]:
arr[-1]

'Data science'

In [12]:
arr[1]

'Kesav'

In [13]:
l[1]

'Kesav'

In [14]:
l[2:4]

[(12+9j), 'Data science']

In [15]:
arr[2:4]

array(['(12+9j)', 'Data science'], dtype='<U64')

In [16]:
for i in l:
    print(i)

arjun
Kesav
(12+9j)
Data science


In [17]:
for i in arr:
    print(i)

arjun
Kesav
(12+9j)
Data science


In [20]:
#Ans -:

In [21]:
type(l)

list

In [22]:
type(arr)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [24]:
l = ["arjun",43.65,True,8+90j]
arr1 = np.array(l)

In [25]:
for i in l:
    print(i," -> ",type(i))

arjun  ->  <class 'str'>
43.65  ->  <class 'float'>
True  ->  <class 'bool'>
(8+90j)  ->  <class 'complex'>


In [26]:
for i in arr1:
    print(i," -> ",type(i))

arjun  ->  <class 'numpy.str_'>
43.65  ->  <class 'numpy.str_'>
True  ->  <class 'numpy.str_'>
(8+90j)  ->  <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Ans-:
In the case of this exaple In list all data in this list type is str but when convert list into the numpy array all data types in the list change in the int.

In [28]:
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

In [30]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [31]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [35]:
l = ["arjun","mukesh","2",21]

In [36]:
a1 = np.array(l)

In [37]:
for i in a1:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [38]:
l = [12,43,56.54]

In [39]:
a1 = np.array(l)

In [40]:
for i in a1:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [41]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [45]:
for i in num_array:
    for j in i:
        print(type(j))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [44]:
for i in num_list:
    for j in i:
        print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [46]:
num_array.shape

(2, 3)

In [47]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [48]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])