In [1]:
import numpy as np
import pandas as pd

In [2]:
l = [12,43,56,86]

In [3]:
np.array(l)

array([12, 43, 56, 86])

In [4]:
np.asanyarray(l)

array([12, 43, 56, 86])

In [5]:
np.asarray(l)

array([12, 43, 56, 86])

In [6]:
arr1 = np.array([1,2,3,4,5])

In [7]:
a = arr1

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
a[0]=1000000

In [10]:
a

array([1000000,       2,       3,       4,       5])

In [11]:
arr1

array([1000000,       2,       3,       4,       5])

In [12]:
b = arr1.copy()

In [13]:
b

array([1000000,       2,       3,       4,       5])

In [14]:
b[0] = 1

In [15]:
b

array([1, 2, 3, 4, 5])

In [16]:
arr1

array([1000000,       2,       3,       4,       5])

In [17]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [18]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.fromstring("12 32 45 65 23 43",sep=" ")

array([12., 32., 45., 65., 23., 43.])

In [21]:
np.fromstring("12,32,45,65,76",sep=",")

array([12., 32., 45., 65., 76.])

In [22]:
np.fromstring("12|21|43|56|54|23",sep="|")

array([12., 21., 43., 56., 54., 23.])

In [23]:
iter = (i for i  in range(10))

In [25]:
np.fromiter(iter,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [29]:
np.logspace(1,10,20,base=2)

array([   2.        ,    2.77730229,    3.85670399,    5.3556164 ,
          7.43708284,   10.32751358,   14.34131354,   19.91508143,
         27.65510059,   38.40328703,   53.32876841,   74.05505519,
        102.836637  ,  142.80421347,  198.30523421,  275.37679007,
        382.40229418,  531.02338276,  737.40622722, 1024.        ])

In [30]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [36]:
arr1

array([1000000,       2,       3,       4,       5])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.diag(arr1)

array([[1000000,       0,       0,       0,       0],
       [      0,       2,       0,       0,       0],
       [      0,       0,       3,       0,       0],
       [      0,       0,       0,       4,       0],
       [      0,       0,       0,       0,       5]])

In [40]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2],[3,4],[5,6]])

In [41]:
arr1

array([1, 2, 3, 4, 5])

In [42]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
arr1.size

5

In [44]:
arr1.shape

(5,)

In [45]:
arr1.dtype

dtype('int32')

In [46]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
arr2.size

6

In [49]:
arr2.T

array([[1, 3, 5],
       [2, 4, 6]])

In [52]:
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr3 = np.random.randn(3,4)

In [55]:
arr3

array([[-7.70281191e-03, -6.63830656e-01,  6.18552781e-04,
         3.22295675e-01],
       [ 4.42391171e-01, -4.20320274e-02, -4.82016888e-01,
        -1.20552626e-01],
       [ 6.08920096e-01,  3.76975624e-01, -1.05331633e+00,
        -3.80720221e-01]])

In [56]:
np.random.randint(1,100,(4,4))

array([[33, 70, 18, 57],
       [50, 22, 96, 94],
       [92, 25, 90, 17],
       [87,  2, 34, 87]])

In [58]:
np.random.rand(3,4)

array([[0.31691105, 0.68399672, 0.8320992 , 0.6677333 ],
       [0.67105865, 0.75130409, 0.10634733, 0.56670393],
       [0.53353659, 0.1414189 , 0.04199464, 0.41935045]])

In [59]:
arr4 = np.random.randint(1,10,(3,4))

In [60]:
arr4

array([[5, 1, 4, 6],
       [8, 7, 3, 3],
       [2, 1, 7, 7]])

In [63]:
arr4[1:3,[1,2]]

array([[7, 3],
       [1, 7]])

In [64]:
arr4[0:3,[3]]

array([[6],
       [3],
       [7]])

In [65]:
arr4

array([[5, 1, 4, 6],
       [8, 7, 3, 3],
       [2, 1, 7, 7]])

In [68]:
arr4 = arr4.flatten()

In [67]:
arr4

array([[5, 1, 4, 6],
       [8, 7, 3, 3],
       [2, 1, 7, 7]])

In [69]:
arr4

array([5, 1, 4, 6, 8, 7, 3, 3, 2, 1, 7, 7])

In [71]:
arr = np.array([1,2,0,5,3,7,6,0,0,9,0])

In [72]:
np.count_nonzero(arr)

7

In [73]:
np.extract(arr==0,arr)

array([0, 0, 0, 0])

In [75]:
np.searchsorted(arr,4)

5

In [76]:
a = np.array([[1],[2],[3],[4]])

In [77]:
a

array([[1],
       [2],
       [3],
       [4]])

In [78]:
a.squeeze()

array([1, 2, 3, 4])

In [79]:
a = np.array([4,3,1,6,2,8,7,90])

In [80]:
a

array([ 4,  3,  1,  6,  2,  8,  7, 90])

In [81]:
a.sort()

In [82]:
a

array([ 1,  2,  3,  4,  6,  7,  8, 90])

In [83]:
arr1 = np.random.randint(1,10,(3,3))

In [84]:
arr2 = np.random.randint(1,10,(3,3))

In [85]:
arr1+arr2

array([[15, 11,  7],
       [10,  9, 14],
       [ 8,  6,  7]])

In [86]:
arr1-arr2

array([[ 1,  5,  3],
       [ 4, -3,  0],
       [-4, -4,  3]])

In [87]:
arr1*arr2

array([[56, 24, 10],
       [21, 18, 49],
       [12,  5, 10]])

In [89]:
arr1/0

C:\Users\shekh\AppData\Local\Temp\ipykernel_7580\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [90]:
arr1@arr2

array([[110,  97,  82],
       [100,  74,  49],
       [ 47,  37,  21]])

In [91]:
arr1.mean()

5.111111111111111

In [92]:
arr1.std()

2.469567863432541

In [93]:
arr1.var()

6.098765432098765

In [94]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.28366219],
       [ 0.75390225, -0.9899925 ,  0.75390225],
       [-0.41614684,  0.54030231,  0.28366219]])

In [95]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825, -0.95892427],
       [ 0.6569866 ,  0.14112001,  0.6569866 ],
       [ 0.90929743,  0.84147098, -0.95892427]])

In [96]:
np.power(arr1,10)

array([[1073741824, 1073741824,    9765625],
       [ 282475249,      59049,  282475249],
       [      1024,          1,    9765625]], dtype=int32)

In [97]:
np.dot(arr1,arr2)

array([[110,  97,  82],
       [100,  74,  49],
       [ 47,  37,  21]])

In [98]:
arr1.T

array([[8, 7, 2],
       [8, 3, 1],
       [5, 7, 5]])

In [99]:
arr1

array([[8, 8, 5],
       [7, 3, 7],
       [2, 1, 5]])

In [100]:
a = np.array([1,2,3,4])

In [101]:
np.roll(a,3)

array([2, 3, 4, 1])

In [102]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [103]:
np.empty((3,4))

array([[0.31691105, 0.68399672, 0.8320992 , 0.6677333 ],
       [0.67105865, 0.75130409, 0.10634733, 0.56670393],
       [0.53353659, 0.1414189 , 0.04199464, 0.41935045]])

In [104]:
np.arange(1,5,0.4)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [105]:
arr1&arr2

array([[0, 0, 0],
       [3, 2, 7],
       [2, 1, 0]])

In [107]:
arr1|arr2

array([[15, 11,  7],
       [ 7,  7,  7],
       [ 6,  5,  7]])

In [108]:
a

array([1, 2, 3, 4])

In [110]:
np.expand_dims(a,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [111]:
a = np.array(['arjun','singh','shekhawat'])

In [112]:
a

array(['arjun', 'singh', 'shekhawat'], dtype='<U9')

In [113]:
np.char.upper(a)

array(['ARJUN', 'SINGH', 'SHEKHAWAT'], dtype='<U9')

In [114]:
np.char.lower(a)

array(['arjun', 'singh', 'shekhawat'], dtype='<U9')

In [115]:
np.char.capitalize(a)

array(['Arjun', 'Singh', 'Shekhawat'], dtype='<U9')

In [116]:
a.dtype

dtype('<U9')

In [117]:
arr1

array([[8, 8, 5],
       [7, 3, 7],
       [2, 1, 5]])

In [118]:
arr1.byteswap()

array([[134217728, 134217728,  83886080],
       [117440512,  50331648, 117440512],
       [ 33554432,  16777216,  83886080]])

In [3]:
import numpy as np
arr = np.array([4,3,2,1,6])

In [4]:
np.argsort(arr)

array([3, 2, 1, 0, 4], dtype=int64)

In [5]:
np.flip(arr)

array([6, 1, 2, 3, 4])

In [15]:
arr1 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
arr2 = np.array([[1,2,3,4,5]])

In [16]:
np.concatenate(arr1)

array([11, 22, 33, 44, 55, 11, 22, 33, 44, 55])

In [17]:
arr1

array([[11, 22, 33, 44, 55],
       [11, 22, 33, 44, 55]])

In [18]:
arr = np.array([1,2,0,0,0,0,3,3,3,3])

In [19]:
np.unique(arr)

array([0, 1, 2, 3])